---
version: "2.0"
services:
  init:
    build: .
    image: pwn3server
  master:
    image: pwn3server
    hostname: master.pwn3
    networks:
      default:
        aliases:
          - "master.pwn3"
    ports:
      - "3333:3333"
    command: "/opt/pwn3/setup/masterserver.sh"
    depends_on:
      - init
  game:
    image: pwn3server
    hostname: game.pwn3
    networks:
      default:
        aliases:
          - "master.pwn3"
    ports:
      - "3000-3010:3000-3010"
    command: "/opt/pwn3/setup/gameserver.sh"
    depends_on:
      - init
      - master
